import os
from setuptools import setup, find_packages

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(PROJECT_ROOT, 'README.md'), encoding='utf-8') as readme:
    README = readme.read()

with open(os.path.join(PROJECT_ROOT, 'requirements.txt'), encoding='utf-8') as reqs:
    requirements = reqs.readlines()

setup(
    name='django-autotranslate',
    version='1.2.0',
    packages=find_packages(),
    install_requires=[req.strip() for req in requirements],
    include_package_data=True,
    license='MIT License',
    description='A simple Django app to automatically translate the pot (`.po`) files generated by django\'s '
                'makemessages command using google translate.',
    long_description=README,
    long_description_content_type='text/markdown',
    url='https://github.com/ankitpopli1891/django-autotranslate/',
    author='Ankit Popli',
    author_email='ankitpopli1891@gmail.com',
    classifiers=[
        'Environment :: Web Environment',
        'Framework :: Django',
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Natural Language :: English',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ],
)